# Site settings
title: LYON SUN
email: sunly917@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  吾生有涯而知无涯
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lyonsun.github.io" # the base hostname & protocol for your site

# Gem settings
plugins: [jekyll-paginate]

# Social settings
twitter_username: lyonsun7
linkedin_username: lyonsun7
github_username:  lyonsun
disqus_shortname:  lyonsun

# Build settings
# markdown: redcarpet
highlighter: rouge
paginate: 1

theme: jekyll-theme-hacker